### ISSUE TITLE
defrag db in etcd-ppc64 does not change its size

### ISSUE THREAD

**Issue by gyuho** [coreos/bbolt#15]
https://jenkins-etcd-public.prod.coreos.systems/job/etcd-ci-ppc64/1876/console

```
--- FAIL: TestMetricDbSizeDefrag (0.64s)
	metrics_test.go:95: expected less than 327680, got 327680 after defrag
```

**Comment by heyitsanthony** [comment]
ppc64 uses 64kb pages (I think; I know arm64 does), but the test only puts 40kb of value data. It's possible it all fits on one page. Try numPuts = 40

**Comment by gyuho** [comment]
https://github.com/coreos/bbolt/issues/15#issuecomment-321700834 worked.

Closing.
