### ISSUE TITLE
Curious about rosdmap

### ISSUE THREAD

**Issue by joeblew99** [coreos/bbolt#39]
The fork has been announced on Reddit.

Are you at a point where you can put any meat on the bones for where bbolt is heading ?

Am excited about this as I use boltdb for almost all projects

**Comment by heyitsanthony** [comment]
@joeblew99 There's no particular roadmap at the moment; new stuff is added as needed. The focus for development is bugfixes, performance enhancements, better integrity checking, better testing, etc. Feel free to open an issue requesting a feature if you have one in mind.

**Comment by joeblew99** [comment]
@heyitsanthony thanks for the feedback.
