### ISSUE TITLE
refuse to start when opening a db created by nofreelistsnyc with freelistsyn option

### ISSUE THREAD

**Issue by xiang90** [coreos/bbolt#5]
DB created with no freelist sync option wont persist freelist down to disk. Opening it with freelist option will fool the db to load in bad freelist, and might cause corruption.

**Comment by heyitsanthony** [comment]
It should probably try to recover instead of only bailing. The freelist page could be set to 0 with NoFreeListSync so that if FreeListSync is enabled, it can see the freelist page is bogus and rebuild.

**Comment by xiang90** [comment]
ah, right. that is another option.
