### ISSUE TITLE
Give proper credit to Ben Johnson

### ISSUE THREAD

**Issue by niemeyer** [coreos/bbolt#53]
Hello folks,

Can we please be more kind to Ben Johnson on the front page of the project? I've been playing with BoltDB and every time I pass through this text I feel bad about it. The relationship with the person that created the project and in fact did a great job doing so, gifting us with good code, good license, good APIs, should really be one of gratitude, but the very first paragraph of the page reads as if we're blaming Ben for not actively changing the project anymore. We're all in that same boat, and it just rubs the wrong way.

Here is a seed idea, but feel free to tune obviously:

_"This is a continuation of Ben Jonhsons' great work on the design and implementation of the original BoltDB package. As the project stabilized, Ben stopped investing as much time on it and we'd like to continue the development preserving the original principles and APIs but improving on some areas such as performance, reliability, and bug fixes when required."_

By the same token, thank you very much for pushing this project forward in those terms and spending your own time on it, openly. I'll most likely be using this on real projects at some point.

**Comment by xiang90** [comment]
@niemeyer can you send a pr instead? thank you.

**Comment by niemeyer** [comment]
Ben himself already spent a huge amount of time on this project. Dedicating a trivial amount of space and time to give proper credit sounds like the bare minimum. But by the end of the day being nice is optional.

For whatever it's worth, I've never met or even talked to Ben.

**Comment by xiang90** [comment]
@niemeyer 

Just to be fair, boltdb is a port from LMDB, which is a port of linux kernel btree + berkeley db API. The credit of LMDB is one line (Bolt is a pure Go key/value store inspired by Howard Chu's LMDB project.).

If you want to help to change the tune of the sentence, I am ok with that. The goal of the readme is to provide a overview of the project, not about his history. If you want to make the article, you probably want to add a history of the project doc?

**Comment by genez** [comment]
I agree that _moribound_ sounds a bit unrespectful
and boltdb was not a mere port of LMDB, but the project evolved a lot thanks to Ben's effort.

**Comment by virtualsue** [comment]
I've submitted a PR which removes 'moribund' but leaves the rest of the README alone.

**Comment by xiang90** [comment]
@niemeyer 

@virtualsue sent a pr to remove "moribund" word. the pr is merged.

again, readme is not the place to talk about the history of the project. we would like to keep it concise. 

if anyone wants to make boltdb better, and continue to help @benbjohnson to improve his great work, please contribute to either boltdb or bboltdb projects.

i am going to close this issue.

**Comment by gyuho** [comment]
https://github.com/coreos/bbolt/pull/56 is merged.
