### ISSUE TITLE
initial release

### ISSUE THREAD

**Issue by gyuho** [coreos/bbolt#7]
Could we cut release (maybe `v1.3.x-coreos`)?
I would like to run functional-tests with latest `bbolt`.

/cc @heyitsanthony @xiang90

**Comment by xiang90** [comment]
let's do this.

**Comment by gyuho** [comment]
@xiang90 I still have no access to `bbolt` :)

**Comment by gyuho** [comment]
I will release `v1.3.1+coreos` once https://github.com/coreos/bbolt/pull/10 is merged.

c.f. https://github.com/coreos/kubernetes/releases

**Comment by gyuho** [comment]
Released https://github.com/coreos/bbolt/releases/tag/v1.3.1-coreos.0.
