### ISSUE TITLE
incremental backup possible?

### ISSUE THREAD

**Issue by gaillard** [coreos/bbolt#93]
The WriteTo is the whole db, is anyone thinking/working on having one that is able to start from an existing backup?
Would be useful so a readonly backup could be used to read and not block updates to another in the case where delayed reads are acceptable.

**Comment by gaillard** [comment]
Nevermind on this at least for the use-case I mentioned, as it appears the copy-on-write semantics mean a read transaction happily reads the already committed data while the write transaction is going until the commit (unless I misunderstand). Fantastic !
Would be great if this fact was mentioned more explicitly in the README, that a write transaction is not literally blocking reads.

**Comment by xiang90** [comment]
You are right in the second comment. @gyuho can you close this issue?
