### ISSUE TITLE
Perfomance: Single put transaction - 20 per second?

### ISSUE THREAD

**Issue by maxim-ge** [coreos/bbolt#94]
Seems bbolt perfomance is 20 "Put transaction"s per second (Windows 7,HDD)
https://github.com/maxim-ge/go-inv/blob/master/bbolt/bbolt_test.go

Use `go test -v -run Test_bbolt_one_per_tr`

Looks as a very low number, is any tuning possible?

PS: SSD is better - 1000 per second

**Comment by maxim-ge** [comment]
E.g. `goleveldb` gives what I would expect from kv database - 100.000 per sec
https://github.com/maxim-ge/go-inv/blob/master/bbolt/goleveldb_test.go

**Comment by maxim-ge** [comment]
`badger` has around 60K per second 
https://github.com/maxim-ge/go-inv/blob/master/bbolt/badger_test.go

**Comment by dtfinch** [comment]
Anything faster on an HDD without a non-volatile cache (typical on server raids, but not desktops) is not guaranteeing durability (the D in ACID).

You can group your Puts into a single db.Update transaction, or use db.Batch (being aware that with Batch your callback will be called at a later time). With that you can make thousands of writes in the same amount of time it takes to make one.

If you want to live dangerously while testing on your desktop, there's also the NoSync option, but it's unsafe and unnecessary on server hardware.

**Comment by maxim-ge** [comment]
Thank you, good explanation, this options leads to 20K per second. 

db.Sync() flushes everything, correct?

**Comment by dtfinch** [comment]
Yeah, DB.Sync() just calls fdatasync() (probably FlushFileBuffers on Windows), which flushes all the block changes to disk. Using Sync() with NoSync is not safe against corruption, if power is lost or the OS crashes mid-sync, because it doesn't guarantee the order that the data is written.
